workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
        CM_CERTIFICATE: "rafal.p12"
        CM_CERTIFICATE_PASSWORD: "QH2wICnyE"
        CM_PROVISIONING_PROFILE: "rafal.mobileprovision"
      node: lts
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS app
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/App.xcarchive archive DEVELOPMENT_TEAM=XHY8V5C8YG PROVISIONING_PROFILE_SPECIFIER=rafal
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/App.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
