workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
      node: lts
      xcode: latest
    ios_signing:
      certificates:
        - certificate: rafal.p12
          certificate_password: "QH2wICnyE"
      provisioning_profiles:
        - profile: rafal.mobileprovision
          certificate: rafal.p12
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS IPA
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace -scheme App -archivePath build/App.xcarchive -destination 'generic/platform=iOS' archive
          xcodebuild -exportArchive -archivePath build/App.xcarchive -exportOptionsPlist exportOptions.plist -exportPath build/ios/ipa
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - rafix1278@gmail.com
      scripts:
        - name: Publish download link
          script: |
            IPA_PATH=$(find build/ios/ipa -name "*.ipa" | head -n 1)
            if [ -f "$IPA_PATH" ]; then
              echo "Aplikacja została pomyślnie zbudowana!"
              echo "Plik IPA jest dostępny do pobrania w artefaktach builda"
            else
              echo "Błąd: Nie znaleziono pliku IPA!"
              exit 1
            fi
