workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m1
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
      node: lts
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          export CI=false
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS
        script: |
          xcodebuild -project ios/App/App.xcodeproj \
                     -scheme App \
                     -configuration Release \
                     -sdk iphoneos \
                     -archivePath $CM_BUILD_DIR/Build/App.xcarchive \
                     -allowProvisioningUpdates \
                     -destination generic/platform=iOS \
                     clean archive
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
