workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
        CM_CERTIFICATE: "rafal.p12"
        CM_CERTIFICATE_PASSWORD: "QH2wICnyE"
        CM_PROVISIONING_PROFILE: "rafal.mobileprovision"
      node: lts
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
      - name: Build iOS App
        script: |
          cd ios/App
          # Tworzenie opcji eksportu
          echo '<?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>development</string>
              <key>signingStyle</key>
              <string>manual</string>
          </dict>
          </plist>' > exportOptions.plist
          # Archiwizacja projektu
          xcodebuild archive \
            -scheme App \
            -archivePath build/App.xcarchive \
            -sdk iphoneos \
            -configuration Release
          # Eksport do .ipa
          xcodebuild exportArchive \
            -archivePath build/App.xcarchive \
            -exportPath build/ios/ipa \
            -exportOptionsPlist exportOptions.plist
    artifacts:
      - path: build/ios/ipa/*.ipa
        name: "iOS_App"
        description: "Pobierz aplikację iOS (.ipa)"
