workflows:
  ios_manual_sign:
    name: iOS Capacitor Manual Signing
    instance_type: mac_mini_m2

    environment:
      groups:
        - ios-certs                     # grupa z Twoim .p12 + .mobileprovision
      node: lts                         # wersja Node.js
      xcode: latest                     # wersja Xcode
      vars:
        DEVELOPMENT_TEAM: "XHY8V5C8YG"  # Twój Apple Team ID

    scripts:
      - name: Install npm & sync Capacitor
        script: |
          npm ci
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Prepare keychain
        script: |
          echo $CM_CERTIFICATE | base64 --decode > /tmp/cert.p12
          security create-keychain -p "" build.keychain
          security import /tmp/cert.p12 \
            -k ~/Library/Keychains/build.keychain \
            -P "$CM_CERTIFICATE_PASSWORD" \
            -T /usr/bin/codesign
          security list-keychains -s ~/Library/Keychains/build.keychain
          security default-keychain -s ~/Library/Keychains/build.keychain

      - name: Install provisioning profile
        script: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo $CM_PROVISIONING_PROFILE | base64 --decode \
            > ~/Library/MobileDevice/Provisioning\ Profiles/$PROVISIONING_PROFILE_UDID.mobileprovision

      - name: Build & Archive
        script: |
          xcodebuild \
            -workspace ios/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Manual \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $CM_BUILD_DIR

    artifacts:
      - $CM_BUILD_DIR/*.ipa

    publishing:
      email:
        recipients:
          - "rafix1278@gmail.com"
        notify:
          success: true
          failure: true

      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id:  $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        submit_to_testflight: false
