workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2

    environment:
      vars:
        DEVELOPMENT_TEAM: "XHVBVSC8YG"
      groups:
        - code_signing

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Setup code signing and Build & Archive
        script: |
          # 1. Create and unlock temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          # 2. Decode and import .p12 certificate
          echo "$CM_P12_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 \
            -k build.keychain \
            -P "$CM_P12_PASSWORD" \
            -T /usr/bin/codesign

          # 3. Decode provisioning profile and extract UUID
          echo "$CM_PROV_PROFILE_BASE64" | base64 --decode > rafal.mobileprovision
          PROFILE_UUID=$(security cms -D -i rafal.mobileprovision | plutil -extract UUID xml1 -o - - | xmllint --xpath 'string(//string)' -)
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp rafal.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/${PROFILE_UUID}.mobileprovision

          # 4. Build & Archive with Manual signing
          xcodebuild -workspace ios/App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -archivePath "$CM_BUILD_DIR/App.xcarchive" \
                     DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
                     CODE_SIGN_STYLE=Manual \
                     CODE_SIGN_IDENTITY="Apple Distribution: Hurtownia Rolno-Ogrodnicza Inagri sp. z o.o. (XHVBVSC8YG)" \
                     PROVISIONING_PROFILE_SPECIFIER="$PROFILE_UUID" \
                     archive

    artifacts:
      - build/App.xcarchive
