workflows:
  ios_manual_sign:
    name: iOS Capacitor Manual Signing
    instance_type: mac_mini_m2

    # ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
    # Sekcja środowiska – tu ładujesz certyfikaty/provisioningi w UI Codemagic
    # ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
        DEVELOPMENT_TEAM: "XHY8V5C8YG"        # Twój Apple Team ID
      groups:
        - ios-certs                          # grupa z Twoim .p12 i .mobileprovision
      node: lts
      xcode: latest

    # ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
    # Skrypty budowania
    # ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
    scripts:
      - name: Install npm dependencies
        script: |
          npm ci

      - name: Sync Capacitor iOS
        script: |
          npx cap sync ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Build & Archive
        script: |
          xcodebuild \
            -workspace ios/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="$CODE_SIGN_IDENTITY" \
            PROVISIONING_PROFILE_SPECIFIER="$PROVISIONING_PROFILE_SPECIFIER" \
            archive

    # ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
    # Publikacja i ręczne podpisywanie
    # ––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––––
    publishing:
      xcode_archive: true

      manual_signing:
        # (1) nazwa Twojego identity, np. "Apple Distribution: Twoja Firma (TEAMID)" albo zmienna:
        code_signing_identity: $CODE_SIGN_IDENTITY

        # (2) mapowanie bundle-ID → provisioning profile UDID
        provisioning_profile_mapping:
          "com.twoja.firma.App": $PROVISIONING_PROFILE_UDID

      email:
        recipients:
          - "rafix1278@gmail.com"
        notify:
          success: true
          failure: true

