workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
        CM_CERTIFICATE: "rafal.p12"
        CM_CERTIFICATE_PASSWORD: "QH2wICnyE"
        CM_PROVISIONING_PROFILE: "rafal.mobileprovision"
      node: lts
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods
        script: |
          cd ios/App
          pod install
    artifacts:
      - ios/App/build/Build/Products/Release-iphoneos/*.ipa
