workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2

    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
        DEVELOPMENT_TEAM: "XHY8V5C8YG"
        CM_CERTIFICATE_PASSWORD: "QH2wICnyE"
      node: lts
      xcode: latest

    scripts:
      - name: Check node and npm versions
        script: |
          node --version
          npm --version

      - name: Install dependencies
        script: |
          npm ci

      - name: Build Capacitor app
        script: |
          npx cap sync ios
          npx cap copy ios

      - name: Install CocoaPods
        script: |
          cd ios
          pod install
          cd ..

      - name: Setup code signing
        script: |
          echo "🔍 Zawartość katalogu roboczego:"
          ls -1

          echo "🔑 Importowanie wszystkich certyfikatów (*.p12):"
          for cert in *.p12; do
            echo " → import $cert"
            security import "$cert" \
              -P "$CM_CERTIFICATE_PASSWORD" \
              -T /usr/bin/codesign
          done

          echo "📦 Instalowanie wszystkich provisioning profiles (*.mobileprovision):"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          for profile in *.mobileprovision; do
            echo " → copy $profile"
            cp "$profile" ~/Library/MobileDevice/Provisioning\ Profiles/
          done

      - name: Build & Archive
        script: |
          xcodebuild \
            -workspace ios/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            CODE_SIGN_IDENTITY="Apple Distribution" \
            archive

      - name: Export IPA
        script: |
          xcodebuild \
            -exportArchive \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath "$CM_BUILD_DIR"

    artifacts:
      - $CM_BUILD_DIR/*.ipa
      - /tmp/xcodebuild_logs/*.log

    publishing:
      email:
        recipients:
          - "rafix1278@gmail.com"
        notify:
          success: true
          failure: true

        

     
   

       
