workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
      node: lts
      xcode: latest
      cocoapods: default
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.dlaroslin.app  # <<< TU PODAJ SWÓJ FAKTYCZNY BUNDLE ID
        export_options:
          method: app-store
    scripts:
      - name: Install dependencies
        script: npm install
      - name: Build web
        script: npm run build
      - name: Sync Capacitor
        script: npx cap sync ios
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - rafix1278@gmail.com
