workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
      node: lts
      xcode: latest
      ios_signing:
        # Codemagic will automatically fetch the correct certificate
        # and provisioning profile matching these parameters
        distribution_type: app_store      # options: app_store | ad_hoc | development | enterprise
        bundle_identifier: pl.dlaroslin.app
    scripts:
      - name: Install dependencies
        script: |
          npm ci
      - name: Build web assets
        script: |
          export CI=false
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Set up code signing settings
        script: |
          # Applies the provisioning profile that Codemagic fetched above
          xcode-project use-profiles
      - name: Build IPA
        script: |
          # Build a signed IPA that can be uploaded straight to App Store Connect
          xcode-project build-ipa             --workspace ios/App/App.xcworkspace             --scheme App
