workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2

    scripts:
      - name: Install JS dependencies
        script: |
          npm ci

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Prepare App resources
        script: |
          # CM_WORKING_DIRECTORY to katalog główny repo
          PROJECT_ROOT="$CM_WORKING_DIRECTORY"

          # Utwórz katalog docelowy
          mkdir -p ios/App

          # Skopiuj pliki konfiguracyjne
          cp "${PROJECT_ROOT}/config.xml" ios/App/config.xml
          cp "${PROJECT_ROOT}/capacitor.config.json" ios/App/capacitor.config.json

          # Skopiuj folder public z głównego katalogu do ios/App/public
          rm -rf ios/App/public
          cp -R "${PROJECT_ROOT}/public" ios/App/public

      - name: Build & Archive (Automatic Signing)
        script: |
          xcodebuild \
            -workspace ios/App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath "$CM_BUILD_DIR/App.xcarchive" \
            -allowProvisioningUpdates \
            archive

    artifacts:
      - build/App.xcarchive
