workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2

    environment:
      vars:
        DEVELOPMENT_TEAM: "XHY8V5C8YG"    # <-- Twój Team ID
        CODE_SIGN_STYLE: "Automatic"      # <-- Wymuszenie stylu podpisu
      groups:
        - code_signing                   # <-- Grupa, w której masz CM_CERTIFICATE, CM_PROV_PROFILE_BASE64, CM_KEYCHAIN_PASSWORD

    scripts:
      - name: Check node and npm versions
        script: |
          node --version
          npm --version

      - name: Install dependencies
        script: |
          npm ci

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build & Archive
        script: |
          xcodebuild -workspace ios/App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -archivePath "$CM_BUILD_DIR/App.xcarchive" \
                     DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
                     -allowProvisioningUpdates \
                     archive

    artifacts:
      - build/App.xcarchive
