workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2

    environment:
      vars:
        DEVELOPMENT_TEAM: "XHVBVSC8YG"
      groups:
        - code_signing

    scripts:
      - name: Check node and npm versions
        script: |
          node --version
          npm --version

      - name: Install dependencies
        script: |
          npm ci

      - name: Setup code signing
        script: |
          # 1. Create and unlock temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain

          # 2. Decode and import .p12 certificate
          echo "$CM_P12_BASE64" | base64 --decode > certificate.p12
          security import certificate.p12 \
            -k build.keychain \
            -P "$CM_P12_PASSWORD" \
            -T /usr/bin/codesign

          # 3. Decode provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo "$CM_PROV_PROFILE_BASE64" | base64 --decode \
            > ~/Library/MobileDevice/Provisioning\ Profiles/rafal.mobileprovision

      - name: List available Xcode schemes in project
        script: |
          xcodebuild -project ios/App.xcodeproj -list

      - name: Build & Archive
        script: |
          xcodebuild -project ios/App.xcodeproj \
                     -scheme App \
                     -configuration Release \
                     -archivePath "$CM_BUILD_DIR/App.xcarchive" \
                     DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
                     CODE_SIGN_STYLE=Manual \
                     PROVISIONING_PROFILE_SPECIFIER="rafal" \
                     archive

    artifacts:
      - build/App.xcarchive
