workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2

    scripts:
      - name: Install JS dependencies
        script: |
          npm ci

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
          cd ..

      - name: Build & Archive (Automatic Signing)
        script: |
          xcodebuild -workspace ios/App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -archivePath "$CM_BUILD_DIR/App.xcarchive" \
                     archive

    artifacts:
      - build/App.xcarchive
