workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2

    environment:
      vars:
        DEVELOPMENT_TEAM: "XHVBVSC8YG"
      groups:
        - code_signing

    scripts:
      - name: Check node and npm versions
        script: |
          node --version
          npm --version

      - name: Install dependencies
        script: |
          npm ci

      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..

      - name: Build & Archive
        script: |
          xcodebuild -workspace ios/App.xcworkspace \
                     -scheme App \
                     -configuration Release \
                     -archivePath "$CM_BUILD_DIR/App.xcarchive" \
                     DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
                     archive

    artifacts:
      - build/App.xcarchive

                   
