workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2

    environment:
      vars:
        # Hasło do pliku .p12 ustaw w Secrets → Environment variables w UI Codemagic jako CM_P12_PASSWORD
        CM_P12_PASSWORD: Encrypted(…)

        # Zespół Developer Team ID
        DEVELOPMENT_TEAM: XHY8V5C8YG

    scripts:
      - name: Install JS dependencies
        script: |
          npm ci

      - name: Install CocoaPods
        script: |
          cd ios
          pod install --repo-update
