workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
        CM_CERTIFICATE: "rafal.p12"              # Plik certyfikatu (masz w repo)
        CM_CERTIFICATE_PASSWORD: "QH2wICnyE"    # Hasło do certyfikatu (twoje)
        CM_PROVISIONING_PROFILE: "rafal.mobileprovision" # Plik provisioning (masz)
      node: lts
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Prepare iOS build
        script: |
          cd ios
          pod install
    artifacts:
      - build/ios/ipa/*.ipa
    ios_signing:
      distribution_type: app_store
      bundle_identifier: "pl.dlaroslin.app"

      
