workflows:
  ios-capacitor-build:
    name: iOS Build (Capacitor)
    instance_type: mac_mini_m2
    environment:
      vars:
        NODE_OPTIONS: "--max_old_space_size=4096"
        CM_CERTIFICATE: "rafal.p12"
        CM_CERTIFICATE_PASSWORD: "QH2wICnyE"
        CM_PROVISIONING_PROFILE: "rafal.mobileprovision"
      node: lts
      xcode: latest
    scripts:
      - name: Install npm dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Clean CocoaPods
        script: |
          cd ios
          rm -rf Pods
          rm -f Podfile.lock
          pod cache clean --all
      - name: Clean Podfile and Create New Podfile
        script: |
          # Usuwanie starego Podfile
          rm -f ios/Podfile
          # Tworzenie nowego Podfile w katalogu ios/
          echo "platform :ios, '13.0'" > ios/Podfile
          echo "" >> ios/Podfile
          echo "project 'App.xcodeproj'" >> ios/Podfile
          echo "" >> ios/Podfile
          echo "target 'App' do" >> ios/Podfile
          echo "  use_frameworks!" >> ios/Podfile
          echo "" >> ios/Podfile
          echo "  pod 'Capacitor'" >> ios/Podfile
          echo "  pod 'CapacitorCordova'" >> ios/Podfile
          echo "end" >> ios/Podfile
      - name: Install CocoaPods
        script: |
          sudo gem install cocoapods
          cd ios
          pod install --repo-update
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Build iOS app
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace -scheme App -configuration Release -sdk iphoneos -archivePath $CM_BUILD_DIR/App.xcarchive archive DEVELOPMENT_TEAM=XHY8V5C8YG PROVISIONING_PROFILE_SPECIFIER=rafal
          xcodebuild -exportArchive -archivePath $CM_BUILD_DIR/App.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath $CM_BUILD_DIR
    artifacts:
      - $CM_BUILD_DIR/*.ipa
