platform :ios, '14.0'
use_frameworks!

target 'dlaroslin-app' do
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
end
